plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.hilt)
    alias(libs.plugins.ksp)
}

android {
    namespace = "com.masterdnsvpn"
    compileSdk = 35

    ndkVersion = "27.3.13750724"

    defaultConfig {
        applicationId = "com.masterdnsvpn"
        minSdk = 26
        targetSdk = 35
        // Read from Gradle properties injected by CI (-PversionCode=X -PversionName=Y)
        // Fallback to hardcoded values for local development.
        versionCode = (project.findProperty("versionCode") as? String)?.toIntOrNull() ?: 9
        versionName = project.findProperty("versionName") as? String ?: "1.0.9"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField(
            "String",
            "UPSTREAM_VERSION",
            "\"${project.findProperty("upstreamVersion") as? String ?: "v2026.04.12.234117-978faee"}\""
        )

        // Include all ABIs in universal APK
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64", "x86")
        }
    }

    signingConfigs {
        create("release") {
            // In CI: set KEYSTORE_PATH, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD env vars.
            // Locally: falls back to the bundled keystore with default credentials.
            storeFile = file(System.getenv("KEYSTORE_PATH") ?: "../masterdnsvpn-release.jks")
            storePassword = System.getenv("KEYSTORE_PASSWORD") ?: "MasterDnsVPN2024!"
            keyAlias = System.getenv("KEY_ALIAS") ?: "masterdnsvpn"
            keyPassword = System.getenv("KEY_PASSWORD") ?: "MasterDnsVPN2024!"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = signingConfigs.getByName("release")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    // Split APKs per ABI (smaller downloads via Play Store)
    splits {
        abi {
            isEnable = true
            reset()
            include("arm64-v8a", "armeabi-v7a", "x86_64", "x86")
            isUniversalApk = true  // also produce a fat universal APK
        }
    }

    // Rename output APKs per ABI (AGP 8.x compatible)
    applicationVariants.all {
        val variant = this
        variant.outputs.map { it as com.android.build.gradle.internal.api.BaseVariantOutputImpl }
            .forEach { output ->
                val abi = output.getFilter(com.android.build.api.variant.FilterConfiguration.FilterType.ABI.name)
                if (abi != null) {
                    output.outputFileName = "MasterDnsVPN-GG-${variant.versionName}-${abi}.apk"
                } else {
                    output.outputFileName = "MasterDnsVPN-GG-${variant.versionName}-universal.apk"
                }
            }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    // Include the gomobile-generated .aar from android/libs/
    // Run android/build_aar.sh first to generate masterdnsvpn.aar.
    repositories {
        google()
        mavenCentral()
        flatDir { dirs("libs") }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    // -----------------------------------------------------------------------
    // gomobile .aar — generated by android/build_aar.sh
    // -----------------------------------------------------------------------
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.aar"))))

    // -----------------------------------------------------------------------
    // AndroidX core
    // -----------------------------------------------------------------------
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.ktx)

    // -----------------------------------------------------------------------
    // Compose BOM + UI
    // -----------------------------------------------------------------------
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons)
    debugImplementation(libs.androidx.compose.ui.tooling)

    // -----------------------------------------------------------------------
    // Navigation
    // -----------------------------------------------------------------------
    implementation(libs.androidx.navigation.compose)

    // -----------------------------------------------------------------------
    // Lifecycle & ViewModel
    // -----------------------------------------------------------------------
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.service)

    // -----------------------------------------------------------------------
    // Hilt
    // -----------------------------------------------------------------------
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.hilt.navigation.compose)

    // -----------------------------------------------------------------------
    // Room
    // -----------------------------------------------------------------------
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    // -----------------------------------------------------------------------
    // DataStore
    // -----------------------------------------------------------------------
    implementation(libs.datastore.preferences)

    // -----------------------------------------------------------------------
    // Security (Keystore-backed encryption for profile keys)
    // -----------------------------------------------------------------------
    implementation(libs.security.crypto)

    // -----------------------------------------------------------------------
    // Coroutines
    // -----------------------------------------------------------------------
    implementation(libs.coroutines.android)

    // -----------------------------------------------------------------------
    // JSON
    // -----------------------------------------------------------------------
    implementation(libs.gson)
}
